export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const NEW_USER = "NEW_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ONE_USER = "GET_ONE_USER";
export const FILTER_USERS_BY_LOCATION = "FILTER_USERS_BY_LOCATION";
